# Generated by Django 5.0.2 on 2024-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_activate_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tg_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
