# Generated by Django 5.0.2 on 2024-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0003_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='users.userprofile'),
        ),
    ]
